//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webFormsForRawWcf.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyContract")]
    public interface IMyContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyContract/MyMethod", ReplyAction="http://tempuri.org/IMyContract/MyMethodResponse")]
        string MyMethod(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyContract/MyMethod", ReplyAction="http://tempuri.org/IMyContract/MyMethodResponse")]
        System.Threading.Tasks.Task<string> MyMethodAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyContractChannel : webFormsForRawWcf.ServiceReference1.IMyContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyContractClient : System.ServiceModel.ClientBase<webFormsForRawWcf.ServiceReference1.IMyContract>, webFormsForRawWcf.ServiceReference1.IMyContract {
        
        public MyContractClient() {
        }
        
        public MyContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string MyMethod(string data) {
            return base.Channel.MyMethod(data);
        }
        
        public System.Threading.Tasks.Task<string> MyMethodAsync(string data) {
            return base.Channel.MyMethodAsync(data);
        }
    }
}
